"""initial schema

Revision ID: 4c2176d8dd94
Revises: 
Create Date: 2026-07-21 16:18:12.213111
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '4c2176d8dd94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('style_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('beneficiary_name', sa.String(length=255), nullable=False),
    sa.Column('field_of_endeavor', sa.String(length=255), nullable=True),
    sa.Column('visa_category', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('filing_deadline', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('intake', 'analyzing', 'strategy_review', 'drafting', 'draft_review', 'ready_to_file', 'filed', 'rfe_received', 'rfe_review', 'approved', 'denied')", name='ck_cases_status'),
    sa.CheckConstraint("visa_category IN ('O-1A', 'EB-1A')", name='ck_cases_visa_category'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_firm_id'), 'cases', ['firm_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('firm_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=True),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('criterion', 'authority', 'pattern', 'precedent')", name='ck_knowledge_chunks_kind'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_criterion_key'), 'knowledge_chunks', ['criterion_key'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_firm_id'), 'knowledge_chunks', ['firm_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','partner','associate','paralegal')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firm_id'), 'users', ['firm_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('graph', sa.String(length=20), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_gate', sa.String(length=50), nullable=True),
    sa.Column('gate_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("graph IN ('petition', 'rfe')", name='ck_agent_runs_graph'),
    sa.CheckConstraint("status IN ('running', 'waiting_review', 'completed', 'failed')", name='ck_agent_runs_status'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_agent_runs_case_id'), 'agent_runs', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_firm_id'), 'agent_runs', ['firm_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_firm_id'), 'audit_log', ['firm_id'], unique=False)
    op.create_table('billing_events',
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('petition_package','rfe_response')", name='ck_billing_events_type'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_events_firm_id'), 'billing_events', ['firm_id'], unique=False)
    op.create_table('criterion_assessments',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("verdict IN ('met', 'partial', 'weak', 'absent')", name='ck_criterion_assessments_verdict'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'criterion_key', name='uq_criterion_assessments_case_criterion')
    )
    op.create_index(op.f('ix_criterion_assessments_case_id'), 'criterion_assessments', ['case_id'], unique=False)
    op.create_index(op.f('ix_criterion_assessments_firm_id'), 'criterion_assessments', ['firm_id'], unique=False)
    op.create_table('documents',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('exhibit_label', sa.String(length=16), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.String(), nullable=True),
    sa.Column('classification_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('cv', 'recommendation_letter', 'publication', 'award', 'press', 'employment', 'prior_filing', 'rfe_notice', 'other')", name='ck_documents_kind'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_firm_id'), 'documents', ['firm_id'], unique=False)
    op.create_table('drafts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('petition_letter', 'support_letter', 'expert_letter', 'rfe_response')", name='ck_drafts_kind'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_case_id'), 'drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_drafts_firm_id'), 'drafts', ['firm_id'], unique=False)
    op.create_table('strategy_memos',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('recommended_category', sa.String(length=10), nullable=True),
    sa.Column('viability', sa.String(length=50), nullable=True),
    sa.Column('criteria_to_argue', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criteria_to_abandon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rfe_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.Column('attorney_decision', sa.String(length=20), nullable=True),
    sa.Column('attorney_notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_memos_case_id'), 'strategy_memos', ['case_id'], unique=False)
    op.create_index(op.f('ix_strategy_memos_firm_id'), 'strategy_memos', ['firm_id'], unique=False)
    op.create_table('draft_sections',
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verification_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewer_comment', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('generated', 'needs_attention', 'approved', 'revision_requested')", name='ck_draft_sections_status'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_sections_draft_id'), 'draft_sections', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_sections_firm_id'), 'draft_sections', ['firm_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_facts_case_id'), 'extracted_facts', ['case_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_firm_id'), 'extracted_facts', ['firm_id'], unique=False)
    op.create_table('rfe_notices',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('response_deadline', sa.Date(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfe_notices_case_id'), 'rfe_notices', ['case_id'], unique=False)
    op.create_index(op.f('ix_rfe_notices_firm_id'), 'rfe_notices', ['firm_id'], unique=False)
    op.create_table('citations',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('authority_ref', sa.String(length=255), nullable=True),
    sa.Column('marker', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('exhibit', 'authority')", name='ck_citations_source_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['draft_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_firm_id'), 'citations', ['firm_id'], unique=False)
    op.create_index(op.f('ix_citations_section_id'), 'citations', ['section_id'], unique=False)
    op.create_table('rfe_objections',
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('criterion_key', sa.String(length=100), nullable=True),
    sa.Column('officer_claim', sa.String(), nullable=False),
    sa.Column('deficiency_type', sa.String(length=100), nullable=True),
    sa.Column('rebuttal_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['rfe_notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfe_objections_firm_id'), 'rfe_objections', ['firm_id'], unique=False)
    op.create_index(op.f('ix_rfe_objections_notice_id'), 'rfe_objections', ['notice_id'], unique=False)
    # ### end Alembic commands ###

    # audit_log is append-only: a trigger blocks UPDATE/DELETE for every role, including the
    # table owner (a GRANT-based restriction would not bind the owner) — this is the
    # malpractice-defensibility guarantee from plan §10.
    op.execute(
        """
        CREATE FUNCTION audit_log_block_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only: % is not permitted', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_log_immutable
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_block_mutation()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_log_immutable ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_block_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfe_objections_notice_id'), table_name='rfe_objections')
    op.drop_index(op.f('ix_rfe_objections_firm_id'), table_name='rfe_objections')
    op.drop_table('rfe_objections')
    op.drop_index(op.f('ix_citations_section_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_firm_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_rfe_notices_firm_id'), table_name='rfe_notices')
    op.drop_index(op.f('ix_rfe_notices_case_id'), table_name='rfe_notices')
    op.drop_table('rfe_notices')
    op.drop_index(op.f('ix_extracted_facts_firm_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_case_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_draft_sections_firm_id'), table_name='draft_sections')
    op.drop_index(op.f('ix_draft_sections_draft_id'), table_name='draft_sections')
    op.drop_table('draft_sections')
    op.drop_index(op.f('ix_strategy_memos_firm_id'), table_name='strategy_memos')
    op.drop_index(op.f('ix_strategy_memos_case_id'), table_name='strategy_memos')
    op.drop_table('strategy_memos')
    op.drop_index(op.f('ix_drafts_firm_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_case_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_documents_firm_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_criterion_assessments_firm_id'), table_name='criterion_assessments')
    op.drop_index(op.f('ix_criterion_assessments_case_id'), table_name='criterion_assessments')
    op.drop_table('criterion_assessments')
    op.drop_index(op.f('ix_billing_events_firm_id'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index(op.f('ix_audit_log_firm_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_runs_firm_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_case_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_users_firm_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_knowledge_chunks_firm_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_criterion_key'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_cases_firm_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('firms')
    # ### end Alembic commands ###
