"""add cases.archived soft-delete flag

Revision ID: 5bde01e0c30e
Revises: 0da14565c97a
Create Date: 2026-07-22 17:48:33.141616
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5bde01e0c30e'
down_revision: Union[str, None] = '0da14565c97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default so this applies cleanly against the already-populated `cases` table
    # (every existing row becomes archived=false, not left NULL) -- dropped after backfill so
    # the column matches the model exactly (no default baked into the schema going forward).
    op.add_column('cases', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('cases', 'archived', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'archived')
    # ### end Alembic commands ###
