"""widen citation marker column

Revision ID: c71cabce4bf1
Revises: 4c2176d8dd94
Create Date: 2026-07-21 17:37:35.988613
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c71cabce4bf1'
down_revision: Union[str, None] = '4c2176d8dd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'marker',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'marker',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
